import { getAnthropic, MODEL_HAIKU } from "@/src/llm/client";

export function extractTextFromHtml(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export interface VerbatimResult {
  phrase: string;
  source_url: string;
  source_excerpt: string;
}

const SYSTEM = `You pick a distinctive 5- to 12-word substring from the company
text that captures their voice and would never plausibly be generated by AI.
Output only JSON: {"phrase": "...", "source_excerpt": "..."}. The phrase MUST
appear as an exact substring of the source.`;

export async function selectVerbatimPhrase(input: {
  source_url: string;
  artifact_text: string;
}): Promise<VerbatimResult> {
  const res = await getAnthropic().messages.create({
    model: MODEL_HAIKU,
    max_tokens: 300,
    system: SYSTEM,
    messages: [{ role: "user", content: input.artifact_text.slice(0, 6000) }],
  });
  const text = res.content
    .filter((c) => c.type === "text")
    .map((c) => (c as { text: string }).text)
    .join("")
    .trim()
    .replace(/^```(?:json)?\n?/, "")
    .replace(/\n?```$/, "");
  const parsed = JSON.parse(text) as { phrase: string; source_excerpt: string };
  return { phrase: parsed.phrase, source_excerpt: parsed.source_excerpt, source_url: input.source_url };
}

/** Fetch the company's apply URL or root domain, return distinctive phrase. */
export async function fetchAndSelectVerbatimPhrase(applyUrl: string): Promise<VerbatimResult | null> {
  try {
    const res = await fetch(applyUrl, { headers: { "User-Agent": "job-hunter/1.0" } });
    if (!res.ok) return null;
    const html = await res.text();
    const text = extractTextFromHtml(html);
    if (text.length < 200) return null;
    return await selectVerbatimPhrase({ source_url: applyUrl, artifact_text: text });
  } catch {
    return null;
  }
}
